### ISSUE TITLE
Cometido del Repositorio

### ISSUE THREAD

**Issue by Villanuevand** [firebaseve/firebase-tools-espanol#1]
La idea de este repositorio es explicar y traducir el `readme.md` (incluyendo los comandos) del repositorio `https://github.com/firebase/firebase-tools`. 

Los comandos de se categorizan en: 
- [x]  [Comandos Administrativos](https://github.com/firebase/firebase-tools#administrative-commands)
- [x] [Despliegue y Desarrollo Local](https://github.com/firebase/firebase-tools#deployment-and-local-development)
- [x] [Comandos de Autenticación](https://github.com/firebase/firebase-tools#auth-commands)
- [x] [Comandos de Base de Datos](https://github.com/firebase/firebase-tools#database-commands)
- [x] [Comandos de Cloud Firestore](https://github.com/firebase/firebase-tools#cloud-firestore-commands)
- [x] [Comandos de Cloud Functions](https://github.com/firebase/firebase-tools#cloud-functions-commands)
- [x] [Comando de Hosting](https://github.com/firebase/firebase-tools#hosting-commands)
- [x] [Usando Integración Continua (CI)](https://github.com/firebase/firebase-tools#using-with-ci-systems)
- [x] [Usando como un Módulo](https://github.com/firebase/firebase-tools#using-as-a-module)

**Comment by jobsamuel** [comment]
Comencé a traducir la documentación. Estoy trabajando en la [traduccion-inicial](https://github.com/firebaseve/firebase-tools-espanol/tree/traduccion-inicial) :nerd_face:

**Comment by Villanuevand** [comment]
@jobsamuel .. 

¿Que tal si extraemos cada punto a 1 issue? 

cc @jqEmprendedorVE / @tecnosoftware

**Comment by jobsamuel** [comment]
Propongo que **no se haga de cada punto un _issue_** hasta que la rama [traduccion-inicial](https://github.com/firebaseve/firebase-tools-espanol/tree/traduccion-inicial) este lista. Como dicha traducción no será perfecta y harán falta otros cambios/mejoras, lo mejor será crear _issues_ independientes para todo esos próximos trabajos pendientes :wink:

**Comment by Villanuevand** [comment]
@jobsamuel 

Está bien, vamos a subir una base estable, y cuando se haga el merge hacia `master` hacemos una mejora de todo.... 

Por favor, no olvides ir haciendo - [x]  ***check*** a los items de este issue cuando los tengas "done"

**Comment by jobsamuel** [comment]
Hice un _PR_ con la traducción inicial :books: Échale un ojo a ver :smiley:

**Comment by jobsamuel** [comment]
¿Cerramos este Issue? Ya todo está :white_check_mark:
