### ISSUE TITLE
CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Villanuevand** [firebaseve/firebase-tools-espanol#2]
Crear `contributing.md` para esté repositorio. 

Ya disponible en el repo=> [site-firebase-venezuela](https://github.com/firebaseve/site-firebase-venezuela/blob/develop/.github/CONTRIBUTING.md)

**Comment by jobsamuel** [comment]
Comencé a trabajar pero sin seguir varios de los lineamientos allí expuestos. Bueno, en realidad sí estoy siguiendo los [Tipos de Acciones](https://github.com/firebaseve/site-firebase-venezuela/blob/develop/.github/CONTRIBUTING.md#tipos-acciones) para los _commits_ PERO en español :es::sweat_smile:

**Comment by Villanuevand** [comment]
MIentras no haya lineamientos sobre como trabajar todo es válido...
